'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '@/lib/api';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/components/ui/Toaster';
import { Plus, Bell, X, Loader2, Sparkles, Calendar } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { DEMO_NOTICES } from '@/lib/demoData';

interface Notice {
  id: string;
  title: string;
  body: string;
  ai_summary?: string;
  target_scope: string;
  author_name: string;
  published_at: string;
  created_at: string;
}

const NoticeSchema = z.object({
  title: z.string().min(1, 'Title is required').max(500),
  body: z.string().min(1, 'Content is required'),
  targetScope: z.enum(['all', 'students', 'teachers', 'parents', 'specific_branch', 'specific_year']),
  isBroadcast: z.boolean(),
});

type NoticeForm = z.infer<typeof NoticeSchema>;

export default function NoticesPage() {
  const { user, isDemoMode } = useAuth();
  const toast = useToast();
  const qc = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [selectedNotice, setSelectedNotice] = useState<Notice | null>(null);
  const [demoNotices, setDemoNotices] = useState<Notice[]>(DEMO_NOTICES as Notice[]);

  const { data, isLoading } = useQuery({
    queryKey: ['notices'],
    queryFn: () => api.get('/notices?limit=50').then(r => r.data),
    enabled: !isDemoMode,
  });

  const createMutation = useMutation({
    mutationFn: (data: NoticeForm) => api.post('/notices', data),
    onSuccess: () => {
      toast('success', 'Notice posted! AI summary and WhatsApp broadcast initiated.');
      qc.invalidateQueries({ queryKey: ['notices'] });
      setShowForm(false);
    },
    onError: () => toast('error', 'Failed to post notice'),
  });

  const handleDemoCreate = (formData: NoticeForm) => {
    const newNotice: Notice = {
      id: `notice-demo-${Date.now()}`,
      title: formData.title,
      body: formData.body,
      ai_summary: '• AI summary would appear here in production\n• Three key bullet points generated by Groq\n• Summarising the notice content',
      target_scope: formData.targetScope,
      author_name: 'You (Demo)',
      published_at: new Date().toISOString(),
      created_at: new Date().toISOString(),
    };
    setDemoNotices(prev => [newNotice, ...prev]);
    toast('success', 'Notice posted! (Demo mode — AI summary simulated)');
    setShowForm(false);
  };

  const notices: Notice[] = isDemoMode ? demoNotices : (data?.data ?? []);

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col sm:flex-row sm:items-center gap-3">
        <div className="flex-1 page-header mb-0">
          <h1 className="page-title">Notices</h1>
          <p className="page-subtitle">Campus announcements and important updates</p>
        </div>
        {(user?.role === 'teacher' || user?.role === 'admin') && (
          <button className="btn-primary shrink-0" onClick={() => setShowForm(true)}>
            <Plus className="w-4 h-4" />
            Post Notice
          </button>
        )}
      </div>

      {/* AI info banner for teachers/admin */}
      {(user?.role === 'teacher' || user?.role === 'admin') && (
        <div className="card p-4 flex items-start gap-3" style={{ background: 'var(--bg-badge)', borderColor: 'hsl(246, 50%, 80%)' }}>
          <Sparkles className="w-5 h-5 shrink-0 mt-0.5" style={{ color: 'var(--color-brand-primary)' }} />
          <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
            When you post a notice, AI generates a 3-bullet summary and WhatsApp notifications are sent to all target students.
          </p>
        </div>
      )}

      {/* Create notice modal */}
      {showForm && (
        <NoticeModal
          onSubmit={(data) => {
            if (isDemoMode) {
              handleDemoCreate(data);
            } else {
              createMutation.mutate(data);
            }
          }}
          onClose={() => setShowForm(false)}
          isLoading={createMutation.isPending}
        />
      )}

      {/* Notice detail modal */}
      {selectedNotice && (
        <NoticeDetailModal
          notice={selectedNotice}
          onClose={() => setSelectedNotice(null)}
        />
      )}

      {/* Notices list */}
      {isLoading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="w-6 h-6 animate-spin" style={{ color: 'var(--color-brand-primary)' }} />
        </div>
      ) : notices.length === 0 ? (
        <div className="card p-12 text-center">
          <Bell className="w-12 h-12 mx-auto mb-3" style={{ color: 'var(--text-muted)' }} />
          <p className="font-medium" style={{ color: 'var(--text-primary)' }}>No notices yet</p>
        </div>
      ) : (
        <div className="space-y-3">
          {notices.map((notice) => (
            <button
              key={notice.id}
              className="card p-5 w-full text-left hover:shadow-md transition-all animate-slide-up group"
              onClick={() => setSelectedNotice(notice)}
              aria-label={`View notice: ${notice.title}`}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2 mb-2">
                    <Bell className="w-4 h-4 shrink-0" style={{ color: 'var(--color-brand-primary)' }} />
                    <h3 className="font-semibold text-sm" style={{ color: 'var(--text-primary)' }}>{notice.title}</h3>
                    <span className="badge badge-brand capitalize">{notice.target_scope.replace('_', ' ')}</span>
                  </div>

                  {/* AI Summary preview */}
                  {notice.ai_summary ? (
                    <div className="flex items-start gap-2 mb-2">
                      <Sparkles className="w-3 h-3 shrink-0 mt-1" style={{ color: 'var(--color-brand-primary)' }} />
                      <p className="text-xs line-clamp-2 whitespace-pre-line" style={{ color: 'var(--text-secondary)' }}>
                        {notice.ai_summary}
                      </p>
                    </div>
                  ) : (
                    <p className="text-sm line-clamp-2 mb-2" style={{ color: 'var(--text-secondary)' }}>
                      {notice.body}
                    </p>
                  )}

                  <div className="flex flex-wrap gap-3 text-xs" style={{ color: 'var(--text-muted)' }}>
                    <span>By {notice.author_name}</span>
                    <span>{formatDistanceToNow(new Date(notice.published_at || notice.created_at), { addSuffix: true })}</span>
                  </div>
                </div>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function NoticeModal({
  onSubmit, onClose, isLoading,
}: {
  onSubmit: (data: NoticeForm) => void;
  onClose: () => void;
  isLoading: boolean;
}) {
  const { register, handleSubmit, formState: { errors } } = useForm<NoticeForm>({
    resolver: zodResolver(NoticeSchema),
    defaultValues: { targetScope: 'all', isBroadcast: true },
  });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="notice-modal-title">
      <div className="card w-full max-w-2xl p-6 animate-slide-up max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between mb-5">
          <h2 id="notice-modal-title" className="font-semibold text-lg" style={{ color: 'var(--text-primary)' }}>
            Post Notice
          </h2>
          <button className="btn-ghost p-1" onClick={onClose} aria-label="Close dialog"><X className="w-5 h-5" /></button>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} noValidate className="space-y-4">
          <div>
            <label htmlFor="notice-title" className="label">Title *</label>
            <input id="notice-title" className="input" placeholder="Notice title..." {...register('title')} />
            {errors.title && <p className="text-xs mt-1 text-red-500">{errors.title.message}</p>}
          </div>

          <div>
            <label htmlFor="notice-body" className="label">Content *</label>
            <textarea id="notice-body" className="input" rows={6} placeholder="Notice content..." {...register('body')} />
            {errors.body && <p className="text-xs mt-1 text-red-500">{errors.body.message}</p>}
          </div>

          <div>
            <label htmlFor="notice-scope" className="label">Target Audience</label>
            <select id="notice-scope" className="input" {...register('targetScope')}>
              <option value="all">Everyone</option>
              <option value="students">Students Only</option>
              <option value="teachers">Teachers Only</option>
              <option value="parents">Parents Only</option>
              <option value="specific_branch">Specific Branch</option>
              <option value="specific_year">Specific Year</option>
            </select>
          </div>

          <label className="flex items-center gap-3 cursor-pointer">
            <input type="checkbox" className="rounded" {...register('isBroadcast')} id="notice-broadcast" />
            <div>
              <p className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>WhatsApp Broadcast</p>
              <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Send WhatsApp notification to all target users</p>
            </div>
          </label>

          <div className="flex items-center gap-2 p-3 rounded-lg" style={{ background: 'var(--bg-badge)' }}>
            <Sparkles className="w-4 h-4 shrink-0" style={{ color: 'var(--color-brand-primary)' }} />
            <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>
              AI will automatically generate a 3-bullet summary of this notice.
            </p>
          </div>

          <div className="flex gap-3 pt-2">
            <button type="button" className="btn-secondary flex-1" onClick={onClose}>Cancel</button>
            <button type="submit" className="btn-primary flex-1" disabled={isLoading}>
              {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Post Notice'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

function NoticeDetailModal({ notice, onClose }: { notice: Notice; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="notice-detail-title">
      <div className="card w-full max-w-2xl p-6 animate-slide-up max-h-[90vh] overflow-y-auto">
        <div className="flex items-start justify-between gap-4 mb-4">
          <h2 id="notice-detail-title" className="font-bold text-lg" style={{ color: 'var(--text-primary)' }}>
            {notice.title}
          </h2>
          <button className="btn-ghost p-1 shrink-0" onClick={onClose} aria-label="Close"><X className="w-5 h-5" /></button>
        </div>

        <div className="flex flex-wrap gap-2 mb-4">
          <span className="badge badge-brand capitalize">{notice.target_scope.replace('_', ' ')}</span>
          <span className="text-xs" style={{ color: 'var(--text-muted)' }}>
            By {notice.author_name} · {formatDistanceToNow(new Date(notice.published_at || notice.created_at), { addSuffix: true })}
          </span>
        </div>

        {notice.ai_summary && (
          <div className="card p-4 mb-4" style={{ background: 'var(--bg-badge)', borderColor: 'hsl(246, 50%, 80%)' }}>
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="w-4 h-4" style={{ color: 'var(--color-brand-primary)' }} />
              <p className="text-xs font-semibold" style={{ color: 'var(--text-brand)' }}>AI Summary</p>
            </div>
            <p className="text-sm whitespace-pre-line" style={{ color: 'var(--text-secondary)' }}>{notice.ai_summary}</p>
          </div>
        )}

        <div className="prose prose-sm max-w-none mb-6">
          <p className="text-sm whitespace-pre-wrap" style={{ color: 'var(--text-primary)', lineHeight: '1.7' }}>
            {notice.body}
          </p>
        </div>

        <div className="pt-4 border-t flex justify-end items-center" style={{ borderColor: 'var(--border-subtle)' }}>
          <button className="btn-primary text-xs" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
